name: RDP Free

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP
      run: net user runneradmin Password123!

    - name: Download Ngrok
      run: choco install ngrok -y

    - name: Set Ngrok Auth
      run: ngrok config add-authtoken $env:NGROK_AUTH_TOKEN

    - name: Start Tunnel
      run: ngrok tcp 3389
