name: RDP Free

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: choco install ngrok -y

    - name: Set Ngrok Auth
      run: ngrok config add-authtoken $env:NGROK_AUTH_TOKEN

    - name: Start Tunnel
      run: |
        start ngrok tcp 3389
        timeout /t 3600
